<a href="https://colab.research.google.com/github/moshehaimlevi/examlib2-14-05/blob/main/examlib2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np
from IPython.display import display
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/order_item.csv'
order_item_df = pd.read_csv(file_path)

drive.mount('/content/drive')
file_path = '/content/drive/My Drive/customers.csv'
customers_df = pd.read_csv(file_path)

drive.mount('/content/drive')
file_path = '/content/drive/My Drive/orders.csv'
orders_df = pd.read_csv(file_path)

drive.mount('/content/drive')
file_path = '/content/drive/My Drive/Items.csv'
items_df = pd.read_csv(file_path)

Mounted at /content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
###################### QUESTION NUMBER 2 ######################
############# SECTION C #############
order_item_merged = order_item_df.merge(items_df[['id', 'item_price']], left_on='item_id', right_on='id', how='left')

order_item_merged['total_price'] = order_item_merged['item_price'] * order_item_merged['quantity']

display(order_item_merged[['item_id', 'item_price', 'quantity', 'total_price']])

     item_id  item_price  quantity  total_price
0       10.0      453.85         2       907.70
1       27.0     1283.99         6      7703.94
2       36.0     3256.88         2      6513.76
3       46.0     1606.65         1      1606.65
4       27.0     1283.99         2      2567.98
..       ...         ...       ...          ...
995     24.0     4449.99         2      8899.98
996     32.0     1523.27         8     12186.16
997     10.0      453.85         3      1361.55
998     29.0     4227.36         1      4227.36
999     16.0     3949.97         1      3949.97

[1000 rows x 4 columns]

In [13]:
############# SECTION D #############
order_item_merged = order_item_df.merge(items_df[['id', 'item_price']], left_on='item_id', right_on='id', how='left')

order_item_merged['total_price'] = order_item_merged['item_price'] * order_item_merged['quantity']

display(order_item_merged['total_price'])

0        907.70
1       7703.94
2       6513.76
3       1606.65
4       2567.98
         ...
995     8899.98
996    12186.16
997     1361.55
998     4227.36
999     3949.97
Name: total_price, Length: 1000, dtype: float64

In [18]:
############# SECTION E #############
from IPython.display import display

order_item_merged = order_item_df.merge(items_df[['id', 'item_price']], left_on='item_id', right_on='id', how='left')

order_item_merged['total_price'] = order_item_merged['item_price'] * order_item_merged['quantity']

print("Average Total Price:")
display(order_item_merged['total_price'].mean())

print("\nMinimum Total Price:")
display(order_item_merged['total_price'].min())

print("\nMaximum Total Price:")
display(order_item_merged['total_price'].max())

Average Total Price:

np.float64(6728.2549895833345)

Minimum Total Price:

241.54

Maximum Total Price:

40241.43000000001

In [22]:
############# SECTION F #############
pivot_df = customers_df.pivot_table(
    values='age',
    index='nationallity',
    columns='gender',
    aggfunc='count',
    fill_value=0
)

display(pivot_df)

gender,Agender,Bigender,Female,Genderfluid,Genderqueer,Male,Non-binary,Polygender
nationallity,,,,,,,,
Argentina,1,0,10,1,0,8,0,1
Brazil,0,0,6,0,0,17,2,1
Chile,1,0,13,0,0,8,0,0
China,0,0,4,1,1,9,0,1
France,1,0,15,1,0,9,0,0
Germany,0,0,12,0,0,3,0,1
India,0,0,7,0,0,15,0,0
Isreal,2,1,20,5,1,28,0,2
Italy,0,0,14,0,2,11,0,0
Japan,1,0,12,0,0,8,0,0
Peru,1,0,10,1,0,6,0,0
South Korea,1,1,13,0,0,11,1,0
Spain,1,0,8,1,0,9,0,0
Sweden,0,0,10,2,0,4,0,0
United States,1,2,37,0,0,39,3,0